language: java

jdk:
  - oraclejdk8

env:
  secure: U+R9p4eaA5PsF7F0Vf39pin/18hhVA+SHQzI9/qGXbrYD6kcuoHSqvqkkoEO+r0PoazNyPWTF2ml4XlxN+a6Cb6I+TWA1wxjEksWU9gvz3zpiqrIh8ZPiAPVw8kv8lObAbPZdpNvIYvoJGJHvYvMjpsNm9J99q4eYNEc7ElBiNxOmgm6xYMzXiwdx4t0bOLEcBWd7B2R803/bqfSBqMESMNDGx7OOnZuUWh9GmIyQ23uST99Tu8p7qHUuemAnf9i4EJ37TJR6qPHMLCScWGwCFpY/X+S/lpFIbCetolqYVm3hJPg/VGllSfJlWiY4GY6TK0gm6xCJsnH2IrlNdRwbqeWcOqWzm2O+JIbPAZkhE76QLAKuZ62XvT18unsmPsaP7JXc8RZmiB3Qbp768u7r9A6PQnGU5yiaS4wIhGkPnyOqZOIQ5Gs8ptU0hswYcdD+6GAs0Nw2w3zK+d2rBsmV4LyvU09MlLvJ0IDzUPp42ZFiTnBoBWU4qEv8lpdOigruIW24MHQvgkS1EA0Ltazs/L87i2wq4Y6eOaB5L1dNGfg1XgnRaTQPXHI58qx04VUOKsVH1OxXiNAZ0N2+SWrL2UG3eqKUjsXbTMpmO8Cno/jMasPqqDJXOx6UOFa+ouWsVS2Is972tWMZ2voXdo4l7ba7/K0qvT+KwBt83Lg4L8=
  global:
    secure: DHIATNu6qZ23NabLiDKVt3IDu9iXIbvoa2uEg40mjoIJfG1uTJCrvRnWZFsNxXeVgwabfZhz52cHDUTOgvUxAZYgaFgdz1vJHhfLHz6X8RIu95I0qV4IgAWqqLeOAuQjBCitj1MvpeYgROxuaotF2ONRwjvwBMt5KTrR5E7UEXfmwHmAW5Lkfz0WpmfPjPCQUUeYE8hzTAB76+SVTMzIRRBO7Ada3a4bdKgwVH6P2Ina3VL5em+prmFb+uojaLFS/QynJkytIMLshBp1LdV2l50lmaEJytARAeB+6xxvzBT/0RB9bGEbeNCDWj55V/M9c/J67+HHNd1sMcGtleRCPMK+raxn53ruYLW/sCgv348bEd2fpwLHWoTzKYTVjdLM1KD1l6HUAuRUMOb9mLblKwo3wU2JqQajO7nINGsi1pQBGk2/D++YK39eBXjITpClv8LndPQcv6nX75skRtL6m5ZT7uW5orRH9tovk8+HPyuj8gI5NkiETAzb6QnvRT4e9Z7dK3V8hlWEYVx17gmKJhBS1BlMZE3fizo7InaoVia3Mk70PpAOG8FCbUE+Mt3qDerTAk9h42vcZ8nX4/yFzUZTIe4A9nbZPiPJOpgecPk0ggCcprvMa90EkcYUWP9rHLulXrGF25TCgRl85hZLOGfGkWx93YoqA0aYopnyiLg=

before_script:
  - ./validate.sh
  - mvn package -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - echo "Success!"
  - echo $FOO
  - echo $BAR
